[package]
name = "vega-antenna"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2c-linux = "0.1.2"

[lib]
name = "vega_antenna"